VECTOR_EMBEDDING_MODEL="sentence-transformers/all-MiniLM-L6-v2"
VECTOR_RETRIEVER_MAX_DOCS=10
CROSS_ENCODER_MODEL="cross-encoder/ms-marco-MiniLM-L-6-v2"
CROSS_ENCODER_RELEVANCE_THRUSHOLD = 2.0
LLM_PLATFORM_CHOICES=["ollama"]