FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --upgrade pip

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./pdf_chatbot /app/pdf_chatbot

EXPOSE 8080

CMD ["uvicorn", "pdf_chatbot.main:app", "--host", "0.0.0.0", "--port", "8080"]
