FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --upgrade pip

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./pdf_chatbot /app/pdf_chatbot

EXPOSE 8080

CMD ["python", "-m", "pdf_chatbot.demo"]
